#!/bin/csh
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f
f77 -fbounds-check -c loadinfo.f
f77 -fbounds-check -c masslink.f
f77 -fbounds-check -c readcontrol_tmsce.f
f77 -fbounds-check -c writeEOannual.f
f77 -fbounds-check -c writeEOaveann.f
f77 -fbounds-check -c writeEOdaily.f
f77 -fbounds-check -c writeEOmonthly.f
f77 -fbounds-check -c readcontrol_load.f
f77 -fbounds-check -c getafoload.f
f77 -fbounds-check -c getrpaload.f

f77 -o ../../../bin/etm_and_postproc_P6.exe main.o loadinfo.o masslink.o readcontrol_tmsce.o writeEOannual.o writeEOaveann.o writeEOdaily.o writeEOmonthly.o readcontrol_load.o getafoload.o getrpaload.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

