#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a $usrdir/ttyux.o)

f77 -fbounds-check -c findupstream.f
f77 -fbounds-check -c segdf.f
f77 -fbounds-check -c stationdf.f
f77 -fbounds-check -c getRAbasins.f

#f77 -c main_original_estimator_version.f
#f77 -c main_assign_upstream_segs.f
#f77 -c main_mass_balance_and_instantaneous_bias_method.f
f77 -fbounds-check -c main_just_write_out_check_stations.f
f77 -fbounds-check -c main_mass_balance_and_instantaneous_bias_method_regional_basins.f

# f77 -c KLUGE_for_SLbig.f

#f77 -o ../../../bin/EOF_to_EOS_original_estimator_version.exe main_original_estimator_version.o findupstream.o segdf.o stationdf.o $usrlib
#f77 -o ../../../bin/EOF_to_EOS_median.exe main_assign_upstream_segs.o findupstream.o $usrlib
#f77 -o ../../../bin/EOF_to_EOS_mass_balance_and_instantaneous_bias_method.exe main_mass_balance_and_instantaneous_bias_method.o findupstream.o sumout/sumout.a $usrlib
f77 -o ../../../bin/EOF_to_EOS_mass_balance_and_instantaneous_bias_method_regional_basins.exe main_mass_balance_and_instantaneous_bias_method_regional_basins.o getRAbasins.o findupstream.o sumout/sumout.a $usrlib
set failed = $status; if( $failed == 1 ) exit 1

# f77 -o ../../../bin/EOF_to_EOS_KLUGE_for_SLbig.exe KLUGE_for_SLbig.o findupstream.o sumout/sumout.a $usrlib
f77 -o ../../../bin/EOF_to_EOS_just_write_out_check_stations.exe main_just_write_out_check_stations.o findupstream.o sumout/sumout.a $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
