#!/bin/csh

f77 -fbounds-check -mcmodel=medium -c chars.f
f77 -fbounds-check -mcmodel=medium -c columnorder.f
f77 -fbounds-check -mcmodel=medium -c comment.f
f77 -fbounds-check -mcmodel=medium -c csv.f
f77 -fbounds-check -mcmodel=medium -c dates.f
f77 -fbounds-check -mcmodel=medium -c stopreport.f
f77 -fbounds-check -mcmodel=medium -c wdm.f
f77 -fbounds-check -mcmodel=medium -c writeline.f
f77 -fbounds-check -mcmodel=medium -c fchar.f
f77 -fbounds-check -mcmodel=medium -c findopen.f
f77 -fbounds-check -mcmodel=medium -c correl.f
f77 -fbounds-check -mcmodel=medium -c interpolate.f
f77 -fbounds-check -mcmodel=medium -c readcontrol.f
f77 -fbounds-check -mcmodel=medium -c sort.f
f77 -fbounds-check -mcmodel=medium -c fipstate.f
f77 -fbounds-check -mcmodel=medium -c addvector.f

ar rv ../util_lib.a chars.o columnorder.o comment.o csv.o dates.o findopen.o stopreport.o wdm.o writeline.o fchar.o correl.o interpolate.o readcontrol.o sort.o fipstate.o addvector.o
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

exit 0
