#!/bin/csh
set FC = $argv[1]
$FC -fbounds-check -c main_aveann.f
$FC -fbounds-check -c readDATaveann.f
$FC -fbounds-check -c readEOaveann.f

$FC -fbounds-check -c main_annual.f
$FC -fbounds-check -c readDATannual.f
$FC -fbounds-check -c readEOannual.f

$FC -fbounds-check -c main_monthly.f
$FC -fbounds-check -c readDATmonthly.f
$FC -fbounds-check -c readEOmonthly.f

$FC -fbounds-check -c loadinfosmall.f
$FC -fbounds-check -c masslinksmall.f
$FC -fbounds-check -c getDFmethod.f

$FC -fbounds-check -c main_data_only_aveann.f
$FC -fbounds-check -c main_pssep_only_aveann.f
$FC -fbounds-check -c readPSSEPaveann.f

$FC -fbounds-check -c main_otherDF_aveann.f

$FC -fbounds-check -c main_copy_ps_loads.f
$FC -fbounds-check -c main_copy_ps_loads_otherDF.f

$FC -o ../../../../bin/sumout_otherDF_aveann.exe main_otherDF_aveann.o loadinfosmall.o masslinksmall.o getDFmethod.o readDATaveann.o readEOaveann.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
$FC -o ../../../../bin/sumout_aveann.exe main_aveann.o loadinfosmall.o masslinksmall.o getDFmethod.o readDATaveann.o readEOaveann.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/sumout_data_only_aveann.exe main_data_only_aveann.o loadinfosmall.o masslinksmall.o readDATaveann.o readEOaveann.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/sumout_pssep_only_aveann.exe main_pssep_only_aveann.o loadinfosmall.o masslinksmall.o readPSSEPaveann.o readEOaveann.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/sumout_monthly.exe main_monthly.o loadinfosmall.o masslinksmall.o getDFmethod.o readDATmonthly.o readEOmonthly.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/sumout_annual.exe main_annual.o loadinfosmall.o masslinksmall.o getDFmethod.o readDATannual.o readEOannual.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/copy_ps_loads.exe main_copy_ps_loads.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o
 $FC -o ../../../../bin/copy_ps_loads_otherDF.exe main_copy_ps_loads_otherDF.o ../../../lib/get_lib.a ../../../lib/util_lib.a ../../../lib/ttyux.o

 rm *.o

