#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c binave.f
$FC -fbounds-check -c doconcs.f
$FC -fbounds-check -c doflows.f
$FC -fbounds-check -c main.f
$FC -fbounds-check -c single.f

$FC -o ../../../../bin/obs_only_stats.exe binave.o doconcs.o doflows.o main.o single.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

rm *.o
