#!/bin/csh

f77 -o ../../../../bin/part_observed.exe part_observed.f ../../../lib/util_lib.a
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../../bin/part_daily_simulated.exe part_daily_simulated.f ../../../lib/util_lib.a
set failed = $status; if( $failed == 1 ) exit 1

f77 -c part_sub.f

