#!/bin/csh
set FC = $argv[1]
$FC -mcmodel=medium -fbounds-check -c getriver.f
$FC -mcmodel=medium -fbounds-check -c getvars.f
$FC -mcmodel=medium -fbounds-check -c getwateracres.f
$FC -mcmodel=medium -fbounds-check -c masslink.f
$FC -mcmodel=medium -fbounds-check -c readcontrol_twdm.f
$FC -mcmodel=medium -fbounds-check -c readdailydat.f
$FC -mcmodel=medium -fbounds-check -c readpair.f
$FC -mcmodel=medium -fbounds-check -c readriver.f
$FC -mcmodel=medium -fbounds-check -c riverbay.f
$FC -mcmodel=medium -fbounds-check -c Rmasslink.f

$FC -mcmodel=medium -fbounds-check -c readriverY1Y2.f
$FC -mcmodel=medium -fbounds-check -c readdailydatY1Y2.f
$FC -mcmodel=medium -fbounds-check -c readpairY1Y2.f

$FC -mcmodel=medium -fbounds-check -c getwateracres_mb.f
$FC -mcmodel=medium -fbounds-check -c readdailydat_mb.f
$FC -mcmodel=medium -fbounds-check -c readpair_mb.f

ar rv wqmlib.a getriver.o getvars.o getwateracres.o masslink.o readcontrol_twdm.o readdailydat.o readpair.o readriver.o riverbay.o Rmasslink.o readriverY1Y2.o readdailydatY1Y2.o readpairY1Y2.o getwateracres_mb.o readdailydat_mb.o readpair_mb.o

rm *.o
