#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main_aveann.f
$FC -fbounds-check -c readInAveann.f
$FC -fbounds-check -c getacres.f

 $FC -o ../../../../bin/sumin_aveann.exe main_aveann.o getacres.o readInAveann.o getAtdep/getatdep.a $dsnlib $lib1 $lib2 $lib3 $usrlib 

 rm *.o

