#Reads precip file and label quantiles classes and
#calculates statistics within those classes
#quantiles are points taken at regular intervals from the cumulative distribution function
args <- commandArgs(trailingOnly = TRUE)
#Variables
dataset<-args[1]
land<-args[2]
qyear1<-as.numeric(args[3])
qyear2<-as.numeric(args[4])
year1<-as.numeric(args[5])
year2<-as.numeric(args[6])
#folder<-args[7]

years<-seq(year1,year2,by=1)
Qs<-c("Q20","Q30","Q40","Q50","Q60","Q70","Q80","Q90","Q100")

#Directories and files
wdir<-paste("./../../../../input/scenario/climate/prad/",dataset,"/txt/",sep="")
wdir2<-paste(wdir,"qstats_seasonal_",year1,"_",year2,"/",sep="")

precipfile<-paste(wdir,"daily_",land,".csv",sep="")
exist <- file.exists(precipfile)

if (exist==TRUE) {
  cat(land," ")

##WINTER
  precipdata<-read.csv(file=precipfile)
  attach(precipdata)
  winterdata <- subset(precipdata,month<=3) 
  attach (winterdata)
  maxval<-max(precip.in.,na.rm = TRUE)
  cat(maxval)
#quantile classes
  data <- data.frame(year1=year,month1=month,day1=day,precip1=precip.in.,quantile1=rep(NA))
  data[data<0.0003937008] <- NA #remove data < 0.01mm (0 inches)
  BRKFILE<-paste(wdir2,"qbreaks_winter_",land,"_",qyear1,"_",qyear2,".csv",sep="")
  BRKDAT<-read.csv(BRKFILE)
  attach(BRKDAT)
  QBREAK<-c(Q0[1],Q20[1],Q30[1],Q40[1],Q50[1],Q60[1],Q70[1],Q80[1],Q90[1],maxval)
  data1<-within(data, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
  attach(data1)
#calculate stats
  mean<-mean(precip1,na.rm=TRUE)
  tot<-sum(precip1,na.rm=TRUE)/length(years)
  count<-sum(!is.na(precip1))/length(years)
  mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
  tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)/length(years)
  count.q<-table(quantile1)/length(years)
  file0<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_winter_all.csv",sep="")
  cat("STAT","All",Qs,file=file0,sep=",","\n")
  cat("intensity",mean,mean.q,file=file0,append=TRUE,sep=",","\n")
  cat("total",tot,tot.q,file=file0,append=TRUE,sep=",","\n")
  cat("frequency",count,count.q,file=file0,append=TRUE,sep=",","\n")
#Annual files
  file1<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_winter_intensity.csv",sep="")
  file2<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_winter_total.csv",sep="")
  file3<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_winter_frequency.csv",sep="")
  cat("YEARN","YEAR","STAT","All",Qs,file=file1,sep=",","\n")
  cat("YEARN","YEAR","STAT","All",Qs,file=file2,sep=",","\n")
  cat("YEARN","YEAR","STAT",Qs,file=file3,sep=",","\n")
#calculate stats every year using quantiles classes from the entire period (breaks=qbreak)
  for (i in 1:length(years)){
    yy <- paste(years[i])
    ydata <- subset(data,year1==paste(yy))
    ydata1<-within(ydata, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE)) 
    attach(ydata1)
    y.mean<-mean(precip1,na.rm=TRUE)
    y.tot<-sum(precip1,na.rm=TRUE)
    y.mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
    y.tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)
    y.count.q<-table(quantile1)
    cat(i,yy,"intensity",y.mean,y.mean.q,file=file1,append=TRUE,sep=",","\n")
    cat(i,yy,"total",y.tot,y.tot.q,file=file2,append=TRUE,sep=",","\n")
    cat(i,yy,"frequency",y.count.q,file=file3,append=TRUE,sep=",","\n")
    detach(ydata1)
  }
  detach(data1)
  detach(precipdata)
  detach(winterdata)

##SPRING
  precipdata<-read.csv(file=precipfile)
  attach(precipdata)
  springdata <- subset(precipdata,month>3 & month<=6)
  attach (springdata)
  maxval<-max(precip.in.,na.rm = TRUE)
#quantile classes
  data <- data.frame(year1=year,month1=month,day1=day,precip1=precip.in.,quantile1=rep(NA))
  data[data<0.0003937008] <- NA #remove data < 0.01mm (0 inches)
  BRKFILE<-paste(wdir2,"qbreaks_spring_",land,"_",qyear1,"_",qyear2,".csv",sep="") 
  BRKDAT<-read.csv(BRKFILE)
  attach(BRKDAT)
  QBREAK<-c(Q0[1],Q20[1],Q30[1],Q40[1],Q50[1],Q60[1],Q70[1],Q80[1],Q90[1],maxval)
  data1<-within(data, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
  attach(data1)
#calculate stats
  mean<-mean(precip1,na.rm=TRUE)
  tot<-sum(precip1,na.rm=TRUE)/length(years)
  count<-sum(!is.na(precip1))/length(years)
  mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
  tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)/length(years)
  count.q<-table(quantile1)/length(years)
  file0<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_spring_all.csv",sep="")
  cat("STAT","All",Qs,file=file0,sep=",","\n")
  cat("intensity",mean,mean.q,file=file0,append=TRUE,sep=",","\n")
  cat("total",tot,tot.q,file=file0,append=TRUE,sep=",","\n")
  cat("frequency",count,count.q,file=file0,append=TRUE,sep=",","\n")
#Annual files
  file1<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_spring_intensity.csv",sep="")
  file2<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_spring_total.csv",sep="")
  file3<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_spring_frequency.csv",sep="")
  cat("YEARN","YEAR","STAT","All",Qs,file=file1,sep=",","\n")
  cat("YEARN","YEAR","STAT","All",Qs,file=file2,sep=",","\n")
  cat("YEARN","YEAR","STAT",Qs,file=file3,sep=",","\n")
#calculate stats every year using quantiles classes from the entire period (breaks=qbreak)
  for (i in 1:length(years)){
    yy <- paste(years[i])
    ydata <- subset(data,year1==paste(yy))
    ydata1<-within(ydata, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
    attach(ydata1)
    y.mean<-mean(precip1,na.rm=TRUE)
    y.tot<-sum(precip1,na.rm=TRUE)
    y.mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
    y.tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)
    y.count.q<-table(quantile1)
    cat(i,yy,"intensity",y.mean,y.mean.q,file=file1,append=TRUE,sep=",","\n")
    cat(i,yy,"total",y.tot,y.tot.q,file=file2,append=TRUE,sep=",","\n")
    cat(i,yy,"frequency",y.count.q,file=file3,append=TRUE,sep=",","\n")
    detach(ydata1)
  }
  detach(data1)
  detach(precipdata)
  detach(springdata)

##SUMMER
  precipdata<-read.csv(file=precipfile)
  attach(precipdata)
  summerdata <- subset(precipdata,month>6 & month<=9)
  attach (summerdata)
  maxval<-max(precip.in.,na.rm = TRUE)
#quantile classes
  data <- data.frame(year1=year,month1=month,day1=day,precip1=precip.in.,quantile1=rep(NA))
  data[data<0.0003937008] <- NA #remove data < 0.01mm (0 inches)
  BRKFILE<-paste(wdir2,"qbreaks_summer_",land,"_",qyear1,"_",qyear2,".csv",sep="")
  BRKDAT<-read.csv(BRKFILE)
  attach(BRKDAT)
  QBREAK<-c(Q0[1],Q20[1],Q30[1],Q40[1],Q50[1],Q60[1],Q70[1],Q80[1],Q90[1],maxval)
  data1<-within(data, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
  attach(data1)
#calculate stats
  mean<-mean(precip1,na.rm=TRUE)
  tot<-sum(precip1,na.rm=TRUE)/length(years)
  count<-sum(!is.na(precip1))/length(years)
  mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
  tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)/length(years)
  count.q<-table(quantile1)/length(years)
  file0<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_summer_all.csv",sep="")
  cat("STAT","All",Qs,file=file0,sep=",","\n")
  cat("intensity",mean,mean.q,file=file0,append=TRUE,sep=",","\n")
  cat("total",tot,tot.q,file=file0,append=TRUE,sep=",","\n")
  cat("frequency",count,count.q,file=file0,append=TRUE,sep=",","\n")
#Annual files
  file1<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_summer_intensity.csv",sep="")
  file2<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_summer_total.csv",sep="")
  file3<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_summer_frequency.csv",sep="")
  cat("YEARN","YEAR","STAT","All",Qs,file=file1,sep=",","\n")
  cat("YEARN","YEAR","STAT","All",Qs,file=file2,sep=",","\n")
  cat("YEARN","YEAR","STAT",Qs,file=file3,sep=",","\n")
#calculate stats every year using quantiles classes from the entire period (breaks=qbreak)
  for (i in 1:length(years)){
    yy <- paste(years[i])
    ydata <- subset(data,year1==paste(yy))
    ydata1<-within(ydata, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
    attach(ydata1)
    y.mean<-mean(precip1,na.rm=TRUE)
    y.tot<-sum(precip1,na.rm=TRUE)
    y.mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
    y.tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)
    y.count.q<-table(quantile1)
    cat(i,yy,"intensity",y.mean,y.mean.q,file=file1,append=TRUE,sep=",","\n")
    cat(i,yy,"total",y.tot,y.tot.q,file=file2,append=TRUE,sep=",","\n")
    cat(i,yy,"frequency",y.count.q,file=file3,append=TRUE,sep=",","\n")
    detach(ydata1)
  }
  detach(data1)
  detach(precipdata)
  detach(summerdata)

##FALL
  precipdata<-read.csv(file=precipfile)
  attach(precipdata)
  falldata <- subset(precipdata,month>9 & month<=12)
  attach (falldata)
  maxval<-max(precip.in.,na.rm = TRUE)
#quantile classes
  data <- data.frame(year1=year,month1=month,day1=day,precip1=precip.in.,quantile1=rep(NA))
  data[data<0.0003937008] <- NA #remove data < 0.01mm (0 inches)
  BRKFILE<-paste(wdir2,"qbreaks_fall_",land,"_",qyear1,"_",qyear2,".csv",sep="")
  BRKDAT<-read.csv(BRKFILE)
  attach(BRKDAT)
  QBREAK<-c(Q0[1],Q20[1],Q30[1],Q40[1],Q50[1],Q60[1],Q70[1],Q80[1],Q90[1],maxval)
  data1<-within(data, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
  attach(data1)
#calculate stats
  mean<-mean(precip1,na.rm=TRUE)
  tot<-sum(precip1,na.rm=TRUE)/length(years)
  count<-sum(!is.na(precip1))/length(years)
  mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
  tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)/length(years)
  count.q<-table(quantile1)/length(years)
  file0<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_fall_all.csv",sep="")
  cat("STAT","All",Qs,file=file0,sep=",","\n")
  cat("intensity",mean,mean.q,file=file0,append=TRUE,sep=",","\n")
  cat("total",tot,tot.q,file=file0,append=TRUE,sep=",","\n")
  cat("frequency",count,count.q,file=file0,append=TRUE,sep=",","\n")
#Annual files
  file1<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_fall_intensity.csv",sep="")
  file2<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_fall_total.csv",sep="")
  file3<-paste(wdir2,"qstats_",land,"_",year1,"_",year2,"_fall_frequency.csv",sep="")
  cat("YEARN","YEAR","STAT","All",Qs,file=file1,sep=",","\n")
  cat("YEARN","YEAR","STAT","All",Qs,file=file2,sep=",","\n")
  cat("YEARN","YEAR","STAT",Qs,file=file3,sep=",","\n")
#calculate stats every year using quantiles classes from the entire period (breaks=qbreak)
  for (i in 1:length(years)){
    yy <- paste(years[i])
    ydata <- subset(data,year1==paste(yy))
    ydata1<-within(ydata, quantile1 <- cut(precip1, breaks=QBREAK, labels=1:9, include.lowest = TRUE))
    attach(ydata1)
    y.mean<-mean(precip1,na.rm=TRUE)
    y.tot<-sum(precip1,na.rm=TRUE)
    y.mean.q<-tapply(precip1,quantile1,mean,na.rm=TRUE)
    y.tot.q<-tapply(precip1,quantile1,sum,na.rm=TRUE)
    y.count.q<-table(quantile1)
    cat(i,yy,"intensity",y.mean,y.mean.q,file=file1,append=TRUE,sep=",","\n")
    cat(i,yy,"total",y.tot,y.tot.q,file=file2,append=TRUE,sep=",","\n")
    cat(i,yy,"frequency",y.count.q,file=file3,append=TRUE,sep=",","\n")
    detach(ydata1)
  }
  detach(data1)
  detach(precipdata)
  detach(falldata)

}



