#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c findcolumn.f
$FC -c ioparvar.f
$FC -c gettargets.f
$FC -c gettarscen.f
$FC -c getkeimfac.f

$FC -o ../../../../../bin/calib_SOLIDS.exe main.o findcolumn.o ioparvar.o gettargets.o gettarscen.o getkeimfac.o $usrlib

rm *.o



