#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

 $FC -fbounds-check -c main_create_precip_wdms.f
 $FC -fbounds-check -c change_precip_for_Nov1985_storm.f

$FC -o ../../../bin/create_precip_wdms main_create_precip_wdms.o $dsnlib $usrlib $lib1 $lib2 $lib3
$FC -o ../../../bin/change_precip_for_Nov1985_storm change_precip_for_Nov1985_storm.o $dsnlib $usrlib $lib1 $lib2 $lib3

rm *.o
