C     version information: VERSN = char*64
      VERSN = '@(#)  wdmrx - diagnose problems in a wdm file'
      VERSN = '@(#)  wdmrx - WRIR draft, Kittle, Flynn, Hummel, Lumb'
      VERSN = '@(#)  wdmrx - Contact: Kate Flynn, kmflynn@usgs.gov'
      VERSN = '@(#)  wdmrx - Version 2.0, 1994/05/27 (HASS tape 2)'
      VERSN = '@(#)  wdmrx - Version 3.0, 1996/03/01 (HASS tape 3)'
      VERSN = '@(#)  wdmrx - Version 3.1, updated 1996/12/11'
      VERSN = '@(#)  wdmrx - Version 3.2, updated 1998/03/06'
