#!/bin/csh

set usrdir = ../../../lib
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c main.f
f77 -fbounds-check -c main_otherDF.f
f77 -fbounds-check -c getDFmethod.f
f77 -fbounds-check -c getloads.f
f77 -fbounds-check -c getRvars.f
f77 -fbounds-check -c delinfo.f

f77 -o ../../../../bin/sum_delivery_factor.exe main.o getDFmethod.o getloads.o getRvars.o delinfo.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1
f77 -o ../../../../bin/sum_otherDF_delivery_factor.exe main_otherDF.o getDFmethod.o getloads.o getRvars.o delinfo.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

