************************************************************************
** set of variables that are frequently used in programs that deal    **
**  with land segments to change parameters or count acrage           **
************************************************************************
      integer maxlsegs,nlsegs  ! number of land segments
      parameter (maxlsegs=450)
      character*6 lsegs(maxlsegs)  ! name of land segments

