#!/bin/csh

#rm problem; echo A10001 PQ20140613_01c 1984 1996 1985 1996 0 0 | ../../../code/bin/eofc_debug.exe > output; ls -altr

#if (-e problem) rm problem; echo A10001 NLDc8514HydBeWQ 1984 1996 1985 1996 1 1 | ../../../code/bin/eofc_debug.exe > output; ls -altr
if (-e problem) rm problem; echo A10001 NLDc8514HydBeWQ 1984 2014 1985 2005 1 1 | ../../../code/bin/eofc_debug.exe > output; ls -altr
