#!/bin/csh

 f77 -fbounds-check -c main.f
 f77 -fbounds-check -c make1type.f

 f77 -o ../../../../bin/sumWTMPstats.exe main.o make1type.o ../../../lib/util_lib.a
 set failed = $status; if( $failed == 1 ) exit 1

 rm *.o

