#!/bin/bash

. hspf_config
scenario=$1
basin=$2
base_scenario=`cbp get_config $scenario script BASELINE_SCENARIO_HYDRO`
model=`cbp get_config $scenario script MM_MODEL`
cbp basingen $scenario $basin
segs=`cbp get_riversegs $basin`
if [ $# -gt 2 ]; then
  if [ "$3" != "all" ]; then
    segs=$3
  fi
fi
if [ $# -gt 3 ]; then
  step=$4
fi
# alternative: just do certain segment that need re-running
# Clone runoff (only needs to be done first time)
echo $segs
quad_zero_segs=`cbp get_config $scenario script QUAD_ZERO_SEGS`
for i in $segs; do 
  # check to see if we should skip this one if it is marked as tidal/no river sim
  to_seg=${i: -4}
  if [ "$to_seg" == "0000" ] ; then
    if [ "$quad_zero_segs" == "" ]; then
      echo "Skipping quad zero segment ${i}."
      continue
    fi
    if [[ "$i" =~ "$quad_zero_segs" ]]; then
      echo "Running quad zero segment $i as directed in conf."
    else
      echo "Skipping quad zero segment ${i}."
      continue
    fi
  fi
  jobname=`cbp mm_job_name $scenario $i`;
  # skip if already running
  job_id=`mm_job_id $jobname`
  if [ "$job_id" != "" ]; then
    echo "$jobname is already running as $job_id"
    continue
  fi

  deps=`cbp mm_river_deps $scenario $i`; 
  echo "sbatch --job-name=$jobname $deps run_model $model $scenario $i auto river analyze $step"; 
  FORCE_RERUN=1;export FORCE_RERUN; sbatch --job-name=$jobname $deps run_model $model $scenario $i auto river analyze $step;
done
