#!/bin/bash
. hspf_config
if [ $# -lt 2 ]; then
  echo "Use: srun_met2river scenario basin [met=1] [land=1] [river=1]"
  exit
fi
scenario=$1
basin=$2
met=1
land=1
river=1
if [ $# -gt 2 ]; then
  met=$3
  if [ $# -gt 3 ]; then 
    land=$4
    if [ $# -gt 4 ]; then 
      river=$5
    fi
  fi
fi

base_scenario=`cbp get_config $scenario script BASELINE_SCENARIO_HYDRO`
model=`cbp get_config $scenario script MM_MODEL`
segs=`cbp get_riversegs $basin`
cbp basingen $scenario $basin
land_segs=`cbp get_landsegs $basin`
met_scenario=`cbp get_config $scenario land "PRECIP ATMOS DEPOSITION"`
baseline_met=`cbp get_config $met_scenario met BASELINE_MET_SCENARIO`
refresh_baseline_met=`cbp get_config $met_scenario met REFRESH_BASELINE_MET`
# run WDM import
# this still needs these it seems?
MODEL_ROOT=$NLDAS_ROOT
SCRIPT_DIR=/opt/model/model_meteorology/sh
export MODEL_ROOT SCRIPT_DIR
if [ "$met" == "1" ]; then
  for i in $land_segs; do
    if [ "$refresh_baseline_met" == "1" ]; then
      job_name=`mm_job_name $baseline_met $i`
      job_id=`mm_job_id $job_name`
      # skip if already running
      if [ "$job_id" != "" ]; then
        echo "$job_name is already running as $job_id"
        continue
      fi
      met_upyears=`cbp get_config $baseline_met met UPDATE_YEARS`
      MSTART_DATE=`cbp get_config $baseline_met met START_DATE`
      MEND_DATE=`cbp get_config $baseline_met met END_DATE`
      msdate=`date -d "$MSTART_DATE" +"%Y%m%d"`
      medate=`date -d "$MEND_DATE" +"%Y%m%d"`
      if [ "$baseline_met" == "met2date" ]; then
        echo "sbatch --job-name="$job_name" $NLDAS_ROOT/make_met2date $i $msdate $medate \"$met_upyears\" landseg"
        sbatch --job-name="$job_name" $NLDAS_ROOT/make_met2date $i $msdate $medate "$met_upyears" landseg
      else
        echo "Error: Can only handle BASELINE_MET_SCENARIO = 'met2date'. set REFRESH_BASELINE_MET = 0."
        echo "Error: Can only handle BASELINE_MET_SCENARIO = 'met2date'. set REFRESH_BASELINE_MET = 0." >> problem
      fi
    fi
  done
fi

if [ "$met" == "1" ]; then
  for i in $land_segs; do
    # check for baseline met dependency
    dep_name=`mm_job_name $baseline_met $i`
    dep_str=""
    dep_ids=`mm_job_id $dep_name`
    job_name=`mm_job_name $met_scenario $i`
    if [ "$dep_ids" != "" ]; then
      dep_str="--dependency=afterok:$dep_ids"
    fi
    MET_PROCESS_METHOD=`cbp get_config $met_scenario met MET_PROCESS_METHOD`
    # TODO: maybe alt should just be another step in the wdm workflow?
    #       or in the geo workflow?
    if [ "$MET_PROCESS_METHOD" == 'alt' ]; then
      # spawn the alt first, with the same baseline dependency
      alt_job_name="alt_$job_name"
      # skip if already running
      alt_job_id=`mm_job_id $alt_job_name`
      if [ "$alt_job_id" == "" ]; then
        echo "sbatch --job-name=\"$alt_job_name\" $dep_str run_model raster_met $met_scenario $i auto alt "
        sbatch --job-name="$alt_job_name" $dep_str run_model raster_met $met_scenario $i auto alt 
        alt_id=`mm_job_id $alt_job_name`
        dep_str="--dependency=afterok:$alt_id"
      fi
    fi
    # skip if already running
    job_id=`mm_job_id $job_name`
    if [ "$job_id" != "" ]; then
      echo "$job_name is already running as $job_id"
      continue
    fi
    echo "sbatch --job-name=\"$job_name\" $dep_str run_model raster_met $met_scenario $i auto wdm "
    sbatch --job-name="$job_name" $dep_str run_model raster_met $met_scenario $i auto wdm 
  done
fi

# Now, I don't think we need these either, as this shold be set by .hspf_config?  We need to streamline
# set needed environment vars
MODEL_ROOT=$CBP_ROOT
export MODEL_ROOT
. hspf_config
# run land
# using dependencies can be submitted immediately after running the wdm import and will wait till completed

if [ "$land" == "1" ]; then
  location="p6_vadeq" # crucial to avoid collisions if running multiple installs
  read -r scope land_scenario < <(cbp get_config $scenario river "LAND SCENARIO")
  for i in $land_segs; do
    job_name=`cbp mm_job_name $scenario $i`
    dep_name=`mm_job_name $met_scenario $i`
    djid=`cbp mm_job_id $dep_name`
    deps=""
    if [ "$djid" != "" ]; then
       deps="--dependency=$djid"
    fi
    # skip if already running
    job_id=`mm_job_id $job_name`
    if [ "$job_id" != "" ]; then
      echo "$job_name is already running as $job_id"
      continue
    fi
    echo "sbatch --job-name=\"$job_name\" $deps run_model $model $land_scenario $i auto land "
    sbatch --job-name="$job_name" $deps run_model $model $land_scenario $i auto land 
  done
fi

# run river
# can now immediately be submitted after submitting land 
# since the dependency ordering works with land and river 
if [ "$river" == "1" ]; then
  segs=`cbp get_riversegs $basin`
  for i in $segs; do
    deps=`cbp mm_river_deps $scenario $i`
    echo "Segment $i Found deps= $deps"
    job_name=`cbp mm_job_name $scenario $i`
    # skip if already running
    job_id=`mm_job_id $job_name`
    if [ "$job_id" != "" ]; then
      echo "$job_name is already running as $job_id"
      continue
    fi
    echo "sbatch --job-name=$job_name $deps run_model $model $scenario $i auto river"
#    sbatch --job-name=$job_name $deps run_model $model $scenario $i auto river
  done
fi

