#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c ioparvar.f
f77 -c gettargets.f
f77 -c gettarscen.f
f77 -c getkeimfac.f

f77 -o ../../../../../bin/calib_SOLIDS.exe main.o findcolumn.o ioparvar.o gettargets.o gettarscen.o getkeimfac.o $usrlib

rm *.o



