#!/bin/csh

set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c main.f
f77 -fbounds-check -c plotinfo.f

f77 -o ../../../../bin/regress_river.exe main.o plotinfo.o $usrlib ../postriverlib.a
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
