#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a

$FC -fbounds-check -c checkriver.f
$FC -fbounds-check -c getl2r.f
$FC -fbounds-check -c getrflags.f
$FC -fbounds-check -c getevap.f
$FC -fbounds-check -c getupstream.f
$FC -fbounds-check -c getallupstream.f
$FC -fbounds-check -c getconseg.f
$FC -fbounds-check -c getlutype.f
$FC -fbounds-check -c readseglist.f
$FC -fbounds-check -c getrsegs.f
$FC -fbounds-check -c getBMPcons.f
$FC -fbounds-check -c getvarfac.f
$FC -fbounds-check -c getl2rlist.f
$FC -fbounds-check -c getpsonlyl2r.f
$FC -fbounds-check -c getconfluence.f

ar rv ../get_lib.a checkriver.o getl2r.o getrflags.o getevap.o getupstream.o getallupstream.o getconseg.o getlutype.o readseglist.o getrsegs.o getBMPcons.o getvarfac.o getl2rlist.o getpsonlyl2r.o

$FC -o ../../../bin/getconfluence.exe getconfluence.o ../../lib/dsn/dsn_utils.o $lib1 $lib2 $lib3 ../../lib/get_lib.a ../../lib/util_lib.a

rm *.o
