#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a $usrdir/ttyux.o)

$FC -fbounds-check -c findupstream.f
$FC -fbounds-check -c segdf.f
$FC -fbounds-check -c stationdf.f
$FC -fbounds-check -c getRAbasins.f

#$FC -c main_original_estimator_version.f
#$FC -c main_assign_upstream_segs.f
#$FC -c main_mass_balance_and_instantaneous_bias_method.f
$FC -fbounds-check -c main_just_write_out_check_stations.f
$FC -fbounds-check -c main_mass_balance_and_instantaneous_bias_method_regional_basins.f

# $FC -c KLUGE_for_SLbig.f

#$FC -o ../../../bin/EOF_to_EOS_original_estimator_version.exe main_original_estimator_version.o findupstream.o segdf.o stationdf.o $usrlib
#$FC -o ../../../bin/EOF_to_EOS_median.exe main_assign_upstream_segs.o findupstream.o $usrlib
#$FC -o ../../../bin/EOF_to_EOS_mass_balance_and_instantaneous_bias_method.exe main_mass_balance_and_instantaneous_bias_method.o findupstream.o sumout/sumout.a $usrlib
$FC -o ../../../bin/EOF_to_EOS_mass_balance_and_instantaneous_bias_method_regional_basins.exe main_mass_balance_and_instantaneous_bias_method_regional_basins.o getRAbasins.o findupstream.o sumout/sumout.a $usrlib
# $FC -o ../../../bin/EOF_to_EOS_KLUGE_for_SLbig.exe KLUGE_for_SLbig.o findupstream.o sumout/sumout.a $usrlib
$FC -o ../../../bin/EOF_to_EOS_just_write_out_check_stations.exe main_just_write_out_check_stations.o findupstream.o sumout/sumout.a $usrlib

rm *.o
