************************************************************************
** set of variables that are frequently used in programs that deal    **
**  with point sources, septic and atmospheric deposition             **
************************************************************************
      character*3 wwtp,cso,indus,sep,rib,rpa,atdep         ! atdep, pointsource, or septic
      data wwtp,cso,indus,sep,rib,rpa,atdep 
     .     /'mun','cso','ind','sep','rib','rpa','wat'/
      
      integer lenwwtp,lencso,lenindus,lensep,lenrib,lenrpa,lenatdep 



