#!/bin/bash
# this is a more flexible form of basingen that is also consistent with other commands
# since basingen.csh only wants a fragment of the river segment ID (the 4 number id)
# but all other commands use the full river segment i.e. 
# river segment id=PS5_5200_4380
# unique segid=5200
if [ $# -le 1 ]; then
  echo "Use: cbp basingen scenario riverseg"
  echo "Ex: cbp basingen p600calib PS5_5200_4380"
  echo "Or: cbp basingen p600calib 5200"
fi
 
n=$2
if [ "$n" != "" ]; then 
  #segid only
  seg=$n
else
  seg=`echo "$n"|awk -F'_' '{print $2}'`
fi
result=`cbp basingen.csh $1 $seg`
echo $result
