#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c getparloads.f
$FC -fbounds-check -c getRvars.f
$FC -fbounds-check -c getvars.f
$FC -fbounds-check -c getwateracres.f
$FC -fbounds-check -c loadinfo.f
$FC -fbounds-check -c readcontrol_wdm.f


$FC -o ../../../bin/compare_scen_and_calib.exe main.o getparloads.o getRvars.o getvars.o getwateracres.o loadinfo.o readcontrol_wdm.o $dsnlib $lib1 $lib2 $lib3 $usrlib

rm *.o

