C
C     parameter to dimension special action conditionals
      INTEGER    MXSPCN,MXSPBK,MXSPCH,MXSPCR
      PARAMETER (MXSPCN=2000)
      PARAMETER (MXSPBK=1000)
      PARAMETER (MXSPCH=2000)
      PARAMETER (MXSPCR=4000)
C
C     MXSPCN - maximum number of comparison-conditions
C     MXSPCH - maximum number of conditional chains
C     MXSPBK - maximum number of logical blocks
C     MXSPCR - maximum number of chain references
C
