#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c smrating.f
$FC -fbounds-check -c obrating.f
$FC -fbounds-check -c caloadinfo.f
$FC -fbounds-check -c gethours.f
$FC -fbounds-check -c seperation.f
$FC -fbounds-check -c transform.f

$FC -o ../../../../bin/TSSRating.exe main.o caloadinfo.o seperation.o gethours.o smrating.o obrating.o transform.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

rm *.o
