#!/bin/bash
scenario=$1
river=$2

. hspf_config

model=`cbp get_config $scenario script "MM_MODEL"`

if [ "$model" == "" ]; then
   echo "Scenario $scenario does not have an entry for MM_MODEL in $CBP_ROOT/config/control/script/${scenario}.con"
fi

MODEL_ROOT=$CBP_ROOT
META_MODEL_ROOT=/opt/model/meta_model
IGNORE_PROBLEMS=0 # set this to 1 if you want to plow forward regardless of errors, not advisable but sometimes...
export MODEL_ROOT META_MODEL_ROOT IGNORE_PROBLEMS

segs=`cbp get_riversegs $river`
echo "Running segs in order: $segs"
for i in $segs; do
  /opt/model/meta_model/run_model $model $scenario $i auto river 
done
