#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c ioparvar.f
f77 -c getall.f
f77 -c minmax.f
f77 -c change_lorgn.f
f77 -c change_params.f
f77 -c AMVolat.f
f77 -c getuptk.f
f77 -c read_storage.f
f77 -c change_rorgn.f
f77 -c read_rorgn.f

f77 -o ../../../../../bin/calib_nitr_pas.exe main.o findcolumn.o getcolumns.o ioparvar.o getall.o minmax.o change_lorgn.o change_params.o AMVolat.o getuptk.o read_storage.o change_rorgn.o read_rorgn.o $usrlib

rm *.o



