      real  RRVAL(6)
      real   umaxhr, umaxdy, dnt50, Tzden, dvv,css ,cwwi,cssi,wtno3wi
     .,dddnit ,porop,bedwidd, ength, bedarea, zdpth, wts, dvvhr,fctdv2
     .,cno3w, cno3s,vsoilw, vwater, vol00, wtno3s, wtno3w 
       common /pwdnt1/umaxhr, umaxdy, dnt50, Tzden, dvv, css ,cwwi,cssi,
     .   wtno3wi
       common /pwdnt2/porop,bedwidd, ength,bedarea, zdpth,dvvhr,fctdv2
       common /pwdnt3/cno3w, cno3s,vsoilw, vwater, vol00, wtno3s, wtno3w
     .       , RRVAL
!      common /pwdnt4/dddnit
