#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f
f77 -fbounds-check -c single.f
f77 -fbounds-check -c loadinfo.f
f77 -fbounds-check -c concinfo.f
f77 -fbounds-check -c gethours.f
f77 -fbounds-check -c flowstats.f
f77 -fbounds-check -c wqstats.f
f77 -fbounds-check -c wqstatsld.f
f77 -fbounds-check -c peaks.f
f77 -fbounds-check -c plt2cal.f
f77 -fbounds-check -c doflows.f
f77 -fbounds-check -c doloads.f
f77 -fbounds-check -c doconcs.f
f77 -fbounds-check -c readtau.f
f77 -fbounds-check -c windowstats.f
f77 -fbounds-check -c monthlybias.f
f77 -fbounds-check -c vodkatest.f
f77 -fbounds-check -c VAstats.f
f77 -fbounds-check -c avmoneff.f
f77 -fbounds-check -c bflowstats.f
f77 -fbounds-check -c eval.f
f77 -fbounds-check -c doflows_write_obs.f

f77 -o ../../../../bin/Rstats_AKLeight.exe loadinfo.o concinfo.o main.o flowstats.o wqstats.o wqstatsld.o gethours.o single.o peaks.o plt2cal.o doflows.o doloads.o doconcs.o readtau.o windowstats.o monthlybias.o vodkatest.o VAstats.o avmoneff.o bflowstats.o eval.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o
set failed = $status; if( $failed == 1 ) exit 1

#f77 -o ../../../../bin/Rstats_write_obs.exe loadinfo.o concinfo.o main.o flowstats.o wqstats.o gethours.o single.o peaks.o plt2cal.o doflows_write_obs.o doloads.o doconcs.o readtau.o windowstats.o monthlybias.o vodkatest.o VAstats.o avmoneff.o bflowstats.o eval.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

rm *.o
