#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c proc.f
$FC -c findcolumn.f
$FC -c doaction.f
$FC -c main_one_line_read.f

$FC -o ../../../../bin/change_params.exe main.o proc.o findcolumn.o doaction.o $usrlib

$FC -o ../../../../bin/change_params_one_line.exe main_one_line_read.o proc.o findcolumn.o doaction.o $usrlib

rm *.o
