#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -c main_aveann.f
f77 -c readInAveann.f
f77 -c getacres.f

f77 -o ../../../../bin/sumin_aveann_QA.exe main_aveann.o getacres.o readInAveann.o getAtdep/getatdep.a $dsnlib $lib1 $lib2 $lib3 $usrlib 
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

