#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main_calib.f
$FC -fbounds-check -c main_year_scenario_from_calib.f
$FC -fbounds-check -c main_scenario_from_scenario_csv.f

$FC -o ../../../bin/create_calib_septic_wdms main_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3

$FC -o ../../../bin/create_year_scenario_septic_wdms_from_calib main_year_scenario_from_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3

$FC -o ../../../bin/create_septic_wdms_from_scenario_csv main_scenario_from_scenario_csv.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
