#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)


f77 -fbounds-check -c -O fix_negatives.f
f77 -fbounds-check -c -O getbmpbreaks.f
f77 -fbounds-check -c -O getbmpspecs.f
#f77 -fbounds-check -c -O gethgmr.f
f77 -fbounds-check -c -O getlandbreaks.f
f77 -fbounds-check -c -O gettransport_l2w.f
f77 -fbounds-check -c -O gettransport_s2r.f
f77 -fbounds-check -c -O getpoundbreaksEOS.f
f77 -fbounds-check -c -O getpoundbreaksEOT.f
#f77 -fbounds-check -c -O hydroeffect.f
f77 -fbounds-check -c -O main.f
f77 -fbounds-check -c -O maketransfile.f
#f77 -fbounds-check -c -O randomeffect.f
f77 -fbounds-check -c -O readcontrol.f
#f77 -fbounds-check -c -O returnfq.f
f77 -fbounds-check -c -O sortB.f

f77 -O -o ../../../bin/bmp_pass_through.exe fix_negatives.o getbmpbreaks.o getbmpspecs.o getlandbreaks.o gettransport_l2w.o gettransport_s2r.o getpoundbreaksEOS.o getpoundbreaksEOT.o main.o maketransfile.o readcontrol.o sortB.o $usrlib ../../lib/dsn/dsn_utils.o $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

