# This script will convert the hydr csv to a data table and perform analysis & generate graphs 
#install.packages("IHA", repos="http://R-Forge.R-project.org")
#install_github("HARPGroup/hydro-tools", force=TRUE)

suppressPackageStartupMessages(library(data.table)) 
suppressPackageStartupMessages(library(lubridate))
suppressPackageStartupMessages(library(zoo))
suppressPackageStartupMessages(library(plyr))
#suppressPackageStartupMessages(library(PearsonDS))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(R.utils))
suppressPackageStartupMessages(library(stringr))

#setwd("/Users/glenncampagna/Desktop/HARPteam22/Data") # for testing only (Glenn) 
#setwd("/Users/VT_SA/Documents/HARP") # for testing only (Julia)
#hydr <- fread("PL2_5470_5360_hydr.csv") # for testing only
#hydr <- fread("OR1_7700_7980_hydr.csv") # for testing only
#divr <- fread("OR1_7700_7980_divr.csv") # for testing only

# establishing location on server for storing images
omsite = "http://deq1.bse.vt.edu:81"

# Accepting command arguments:
argst <- commandArgs(trailingOnly = T)
hydr_file_path <- argst[1]  
#hydr_file_path <- '/media/model/p532/out/river/hsp2_2022/hydr/OR1_7700_7980_hydr.csv'

hydr <- fread(hydr_file_path)

# Converting from ac-ft/hr (ROVOL) to cfs : 1 ac-ft/hr = 12.1 cfs
hydr$Qout <- hydr$OVOL3*12.1 #Qout in units of cfs
hydr$wd_mgd <- (hydr$RO - hydr$O3) /1.5472 # withdrawal cfs converted to mgd
#hydr$ps_mgd <- hydr$ps_afd*0.32585
hydr$demand_mgd <- (hydr$divr_cfs + hydr$diva_cfs)/1.5472 #demand cfs summed and coverted to mgd 

#Qbaseline = Qout + (wd_cum_mgd - ps_cum_mgd)*1.547
hydr$Qbaseline <- hydr$Qout + (hydr$wd_mgd - hydr$ps_mgd)*1.5472

# Assumptions and placeholder columns
hydr$wd_imp_child_mgd = 0 #child vars used in hspf 
hydr$wd_cumulative_mgd = hydr$wd_mgd  
hydr$ps_cumulative_mgd = hydr$ps_mgd
hydr$ps_nextdown_mgd = 0 

#Write hourly hydr csv
write.table(hydr,file = hydr_file_path, sep = ",", row.names = FALSE)

#For daily hydr csv
daily_path <- str_replace(hydr_file_path, 'hydr.csv', 'hydrd_wy.csv') #create daily path
hydrd = aggregate(hydr, list(hydr$date), 'mean')
hydrd <- subset(hydrd, select= -c(1))  #Removing column generated by aggregation

#trimming to water year and adding the buffer
syear = as.integer(min(hydrd$year))
eyear = as.integer(max(hydrd$year))
model_run_start <- min(hydrd$date)   
model_run_end <- max(hydrd$date)
years <- seq(syear,eyear)

if (syear < (eyear - 2)) {
  sdate <- as.Date(paste0(syear,"-10-01"))
  edate <- as.Date(paste0((eyear-1),"-09-30")) 
  flow_year_type <- 'water'
} else {
  sdate <- as.Date(paste0(syear,"-02-01"))
  edate <- as.Date(paste0(eyear,"-12-31"))
  flow_year_type <- 'calendar'
}

hydrd = aggregate(hydrd, list(hydrd$date),FUN = 'mean') #Adds 'Group.1' col of class date

#Reverted back to using window(), which requires a ts or zoo:
hydrd <- zoo(hydrd, order.by = as.Date(hydrd$Group.1)) 
hydrd <- subset(hydrd, select = -c(Group.1)) #removing col that was added by aggregation

hydrd <- window(hydrd, start = sdate, end = edate)

#Creating vectors for index and date to be passed in later before writing
index <- hydrd$index
date <- hydrd$date

#Convert hydr to numeric
mode(hydrd) <- 'numeric'

#Add the removed columns back to the hydrd zoo (removed by setting zoo to numeric)
hydrd$index <- index
hydrd$date <- date

write.table(hydrd,file = daily_path, sep = ",", row.names = FALSE) #Write daily csv
