#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c rproc.f
f77 -c findcolumn.f
f77 -c doaction.f
f77 -c findtau.f
f77 -c main_one_line_read.f

f77 -o ../../../../bin/Rchange_params.exe main.o rproc.o findcolumn.o doaction.o findtau.o $usrlib

f77 -o ../../../../bin/Rchange_params_one_line.exe main_one_line_read.o rproc.o findcolumn.o doaction.o findtau.o $usrlib

rm *.o
