#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f
f77 -fbounds-check -c plotinfo.f
f77 -fbounds-check -c header.f
f77 -fbounds-check -c ziplabel.f
f77 -fbounds-check -c maindouble.f

f77 -o ../../../../bin/Rdaily.exe plotinfo.o header.o main.o ziplabel.o maindouble.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

