************************************************************************
** this file sets the order of pqual and iqual variables in the input **
**   files.  It MUST be consistent with the files                     **
**   ./pp/catalog/iovars/perlnd and ./pp/catalog/iovars/implnd        **
************************************************************************
      integer knh3,kno3,klon,kron,kpo4,nquals,nq
      parameter (knh3 = 1)
      parameter (kno3 = 2)
      parameter (klon = 3)
      parameter (kron = 4)
      parameter (kpo4 = 5)
      parameter (nquals = 5)
