#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -c main.f
f77 -c rating_SMcensor.f
f77 -c rating_OBcensor.f
f77 -c seperation.f
f77 -c transform.f
f77 -c checkflow.f
f77 -c date.f

f77 -o ../../../bin/TSSRating_censored.exe main.o seperation.o rating_SMcensor.o rating_OBcensor.o transform.o checkflow.o date.o $dsnlib $lib1 $lib2 $lib3 $usrlib ../../postproc/river/part/part_sub.o

rm *.o
