#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c single.f
$FC -fbounds-check -c loadinfo.f
$FC -fbounds-check -c concinfo.f
$FC -fbounds-check -c gethours.f
$FC -fbounds-check -c flowstats.f
$FC -fbounds-check -c wqstats.f
$FC -fbounds-check -c peaks.f
$FC -fbounds-check -c plt2cal.f
$FC -fbounds-check -c doflows.f
$FC -fbounds-check -c doloads.f
$FC -fbounds-check -c doconcs.f
$FC -fbounds-check -c readtau.f
$FC -fbounds-check -c windowstats.f
$FC -fbounds-check -c monthlybias.f
$FC -fbounds-check -c vodkatest.f
$FC -fbounds-check -c VAstats.f
$FC -fbounds-check -c avmoneff.f
$FC -fbounds-check -c bflowstats.f
$FC -fbounds-check -c eval.f
$FC -fbounds-check -c doflows_write_obs.f

$FC -o ../../../../bin/Rstats.exe loadinfo.o concinfo.o main.o flowstats.o wqstats.o gethours.o single.o peaks.o plt2cal.o doflows.o doloads.o doconcs.o readtau.o windowstats.o monthlybias.o vodkatest.o VAstats.o avmoneff.o bflowstats.o eval.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

$FC -o ../../../../bin/Rstats_write_obs.exe loadinfo.o concinfo.o main.o flowstats.o wqstats.o gethours.o single.o peaks.o plt2cal.o doflows_write_obs.o doloads.o doconcs.o readtau.o windowstats.o monthlybias.o vodkatest.o VAstats.o avmoneff.o bflowstats.o eval.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib ../part/part_sub.o

rm *.o
