#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o


f77 -fbounds-check -c summarize_temp_pet.f

f77 -o ../../../bin/summarize_temp_pet.exe summarize_temp_pet.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
