#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -c main_flash10_from_uniform.f
f77 -c main_check_years.f
f77 -c main_write_base.f

f77 -o ../../../bin/flash10_from_uniform main_flash10_from_uniform.o $usrlib $dsnlib $lib1 $lib2 $lib3
f77 -o ../../../bin/check_years main_check_years.o $usrlib $dsnlib $lib1 $lib2 $lib3
f77 -o ../../../bin/write_base main_write_base.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
