C     version information: VERSN = char*64
      VERSN = '@(#) wdimex - build a message file'
      VERSN = '@(#) wdimex - WRIR draft, Kittle, Flynn, Hummel, Lumb'
      VERSN = '@(#) wdimex - Contact: Kate Flynn, kmflynn@usgs.gov'
      VERSN = '@(#) wdimex - Version 2.0, 1994/05/27 (HASS tape 2)'
      VERSN = '@(#) wdimex - Version 3.0, 1996/03/01 (HASS tape 3)'
      VERSN = '@(#) wdimex - Version 3.1, updated 1996/12/11'
      VERSN = '@(#) wdimex - Version 3.2, updated 1998/03/06'
