#!/bin/csh
set FC = $argv[1]
source ../../set_wdmlibdir
set wdmlibdir = ../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set dsnlib = ../lib/dsn/dsn_utils.o

set usrdir = ../lib
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

$FC -fbounds-check -c main.f
$FC -fbounds-check -c readloads.f
$FC -fbounds-check -c readcontrolkey.f
$FC -fbounds-check -c readspeclu.f
$FC -fbounds-check -c rmMissingloads.f

$FC -o ../../bin/create_land_wdm_from_loads.exe main.o readloads.o readcontrolkey.o readspeclu.o rmMissingloads.o $usrlib $dsnlib $lib1 $lib2 $lib3 

rm *.o
