#!/bin/csh

set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c proc.f
f77 -c findcolumn.f
f77 -c doaction.f
f77 -c main_one_line_read.f

f77 -o ../../../../bin/change_params.exe main.o proc.o findcolumn.o doaction.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../../bin/change_params_one_line.exe main_one_line_read.o proc.o findcolumn.o doaction.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
