#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c splitland.f
$FC -c splitriv.f

$FC -o ../../../bin/splitseglists.exe main.o splitland.o splitriv.o $usrlib

rm *.o
