#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c plotinfo.f
$FC -fbounds-check -c header.f
$FC -fbounds-check -c ziplabel.f
$FC -fbounds-check -c maindouble.f

$FC -o ../../../../bin/Rdaily.exe plotinfo.o header.o main.o ziplabel.o maindouble.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib

rm *.o

