#!/bin/csh
set FC = $argv[1]
source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c readplt.f

$FC -o ../../../../bin/create_p4_wdms.exe main.o readplt.o $dsnlib $lib1 $lib2 $lib3 ../../river/postriverlib.a $usrlib

rm *.o

