#!/bin/csh

 set big = $argv[2]

 set little = $argv[1]

 set filetypes = (riv calib land)

 foreach ft ($filetypes)  # loop over file types

   echo $ft

   if (-e ${big}.${ft}) then
     if (-e ${little}.${ft}) then

       source ${big}.${ft}      # read big file
       set bigsegs = ($segments)

       source ${little}.${ft}   # read little file
       set littlesegs = ($segments)
  
       set segments = ($littlesegs)

       foreach bs ($bigsegs)
         set test = '0'
         foreach ls ($littlesegs)
           if ( $bs == $ls ) then
             set test = '1'
           endif
         end
         if ( $test == '0' ) then
           set segments = ($segments $bs)
         endif
       end

       echo 'set segments = (' $segments ')' > ${big}_plus_${little}.${ft}

     endif
   endif

 end

 
