#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c ioparvar.f
f77 -c getall.f
f77 -c change_phos1.f
f77 -c change_phos2.f

f77 -o ../../../../../bin/calib_phos_noncrop.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o change_phos1.o change_phos2.o $usrlib

rm *.o



