#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c read_outfile.f

f77 -c main_read_ON_stor.f

f77 -o ../../../bin/read_dot_out_files_scour.exe read_outfile.o main.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

#f77 -o ../../../bin/read_ON_stor.exe main_read_ON_stor.o $usrlib

rm *.o
