#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../lib/
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

$FC -fbounds-check -c main.f
$FC -fbounds-check -c CalcBasinDFann.f
$FC -fbounds-check -c CalcBasinDFave.f
$FC -fbounds-check -c CalcBasinDFmon.f
$FC -fbounds-check -c CalcResDFann.f
$FC -fbounds-check -c CalcResDFave.f
$FC -fbounds-check -c CalcResDFmon.f
$FC -fbounds-check -c CalcSegDFann.f
$FC -fbounds-check -c CalcSegDFave.f
$FC -fbounds-check -c CalcSegDFmon.f
$FC -fbounds-check -c delinfo.f
$FC -fbounds-check -c downstream.f
$FC -fbounds-check -c findResBasin.f
$FC -fbounds-check -c findupstream.f
$FC -fbounds-check -c getloads.f
$FC -fbounds-check -c getRvars.f
$FC -fbounds-check -c multtfs.f
$FC -fbounds-check -c pourpoint.f
$FC -fbounds-check -c readtfinout.f
$FC -fbounds-check -c writedfs.f


$FC -o ../../../../bin/DFS.exe main.o CalcBasinDFann.o CalcBasinDFave.o CalcBasinDFmon.o CalcResDFann.o CalcResDFave.o CalcResDFmon.o CalcSegDFann.o CalcSegDFave.o CalcSegDFmon.o delinfo.o downstream.o findResBasin.o findupstream.o getloads.o getRvars.o multtfs.o pourpoint.o readtfinout.o writedfs.o $usrlib

rm *.o

