#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set wqmlib = ../wqmlib/wqmlib.a

f77 -c main_nps.f
f77 -c main_ps.f

f77  -o ../../../bin/wqm_factor_scenario_ps_to_wqm57k.exe main_ps.o $wqmlib $usrlib 
f77  -o ../../../bin/wqm_factor_scenario_nps_to_wqm57k.exe main_nps.o $wqmlib $usrlib 

rm *.o
