#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o
set wqmlib = ../wqmlib/wqmlib.a

$FC -fbounds-check -c main_nps.f
$FC -fbounds-check -c main_ps.f

$FC  -o ../../../bin/combine_2wqm_scenarios_ps_to_wqm57k.exe main_ps.o $wqmlib $usrlib $dsnlib $lib1 $lib2 $lib3
$FC  -o ../../../bin/combine_2wqm_scenarios_nps_to_wqm57k.exe main_nps.o $wqmlib $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
