#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f

f77 -o ../../../../config/seglists/reverse_seglist.exe main.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
