#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f

f77 -fbounds-check -c readlcontrol_prad.f
f77 -fbounds-check -c main_prad.f

f77 -fbounds-check -c main_others.f

#f77 -o ../../../../bin/Laveann.exe main.o $dsnlib $lib1 $lib2 $lib3 $usrlib 
#set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../../bin/Laveann_prad.exe readlcontrol_prad.o main_prad.o $dsnlib $lib1 $lib2 $lib3 $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../../bin/Laveann_others.exe readlcontrol_prad.o main_others.o $dsnlib $lib1 $lib2 $lib3 $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
