#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f
f77 -fbounds-check -c readcontrol_vartypes.f
f77 -fbounds-check -c plt2cal.f
f77 -fbounds-check -c loadavann.f
f77 -fbounds-check -c loadinfo.f
f77 -fbounds-check -c gethours.f

f77 -o ../../../../bin/Rpltgen.exe loadinfo.o main.o gethours.o loadavann.o readcontrol_vartypes.o plt2cal.o $dsnlib $lib1 $lib2 $lib3 ../../river/postriverlib.a $usrlib ../../river/part/part_sub.o
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

