#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c findcolumn.f
$FC -c getcolumns.f
$FC -c ioparvar.f
$FC -c getall.f
$FC -c change_phos1.f
$FC -c change_phos2.f
$FC -c getuptakep.f

$FC -o ../../../../../bin/calib_phos_crop.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o change_phos1.o change_phos2.o getuptakep.o $usrlib

rm *.o



