#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c getall.f
$FC -c process.f

$FC -o ../../../bin/riverinfo.exe main.o getall.o process.o $usrlib

$FC -c stand_alone_get_all_rseg_lseg_percents.f
$FC -o ../../../bin/stand_alone_get_all_rseg_lseg_percents.exe stand_alone_get_all_rseg_lseg_percents.o getall.o process.o $usrlib

$FC -c stand_alone_get_downstream_foreach_rseg_lseg.f
$FC -o ../../../bin/stand_alone_get_downstream_foreach_rseg_lseg.exe stand_alone_get_downstream_foreach_rseg_lseg.o getall.o process.o $usrlib

$FC -c stand_alone_get_upstream.f
$FC -o ../../../bin/stand_alone_get_upstream.exe stand_alone_get_upstream.o getall.o process.o $usrlib

rm *.o
