#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -fbounds-check -c main.f
#$FC -fbounds-check -c plotinfo.f
#$FC -fbounds-check -c eval.f
$FC -o ../../../../bin/caltext.exe main.o $usrlib ../postriverlib.a

rm *.o
