************************************************************************
** set of variables that are frequently used in programs that deal    **
**  with point sources, septic and atmospheric deposition             **
************************************************************************
      character*6 wwtp,cso,indus,sep,atdep         ! atdep, pointsource, or septic
      data wwtp,cso,indus,sep,atdep 
     .     /'wwtp','cso','indus','septic','atdep'/
      
      integer lenwwtp,lencso,lenindus,lensep,lenatdep 



