#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c readcontrol_tp.f
$FC -fbounds-check -c resconvert.f
$FC -fbounds-check -c resflo.f
$FC -fbounds-check -c resout.f
$FC -fbounds-check -c Rmasslink.f
$FC -fbounds-check -c readftab.f
$FC -fbounds-check -c getdsn.f

$FC -o ../../../bin/combine_ps_sep_div_ams_from_landsegs.exe main.o readcontrol_tp.o resconvert.o resflo.o resout.o Rmasslink.o readftab.o getdsn.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o

