#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -fbounds-check -c main.f
$FC -fbounds-check -c plotinfo.f

$FC -o ../../../../bin/regress_river.exe main.o plotinfo.o $usrlib ../postriverlib.a

rm *.o
