#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c proc.f
$FC -c findcolumn.f
$FC -c readcontrol_tree2paramscen.f
$FC -c doaction.f
$FC -c getthislutype.f

$FC -o ../../../bin/get1parameter.exe main.o proc.o findcolumn.o readcontrol_tree2paramscen.o doaction.o getthislutype.o $usrlib

rm *.o
