************************************************************************
** declare integers to be the indices for parameters                  **
**  to add more parameters, add a line here and also add appropriate  **
**  calls and passes to getParIndices and newPar subroutines          **
************************************************************************
      integer kREAK
      integer kCFOREA
      integer kSUPSAT
      integer kBENOD

      integer kCTAUCS
      integer kSTAUCS
      integer kCTAUCD
      integer kSTAUCD
      integer kSM
      integer kCM
      integer kCW
      integer kSW
      integer kKSAND
      integer kEXPSND

      integer kPHYSET
      integer kREFSET
      integer kMALGR
      integer kALDL
      integer kTALGRM
      integer kSEED
      integer kMXSTAY

      integer kKTAM20
      integer kKNO320
      integer kDENOXT
      integer kBRPO41
      integer kBRPO42
      integer kBRTAM1
      integer kBRTAM2
      integer kANAER
      integer kBEDNH4SILT
      integer kBEDNH4CLAY
      integer kBEDNH4SAND
      integer kADSNH4SILT
      integer kADSNH4CLAY
      integer kADSNH4SAND
      integer kBEDPO4SILT
      integer kBEDPO4CLAY
      integer kBEDPO4SAND
      integer kADSPO4SILT
      integer kADSPO4CLAY
      integer kADSPO4SAND

