#!/bin/csh

set utillib = '../../lib/util_lib.a'

f77 -mcmodel=medium -fbounds-check -c marjy12.f
f77 -mcmodel=medium -fbounds-check -c getatdepmarjy12.f

f77 -mcmodel=medium -fbounds-check -c getcellarea.f

#f77  -o ../../../bin/atdep36_to_wqm57k_calib.exe main36.o getatdep36.o getcellarea.o $utillib
f77  -o ../../../bin/marjy12_to_wqm57k_calib.exe marjy12.o getatdepmarjy12.o getcellarea.o $utillib
#f77  -o ../../../bin/atdep12_to_wqm57k_year_scenario.exe main12_year_scenario.o getatdep12_year_scenario.o getcellarea.o $utillib
#f77  -o ../../../bin/atdep12_to_wqm57k_CMAQ_scenario.exe main12_CMAQ_scenario.o getatdep12_CMAQ_scenario.o getcellarea.o $utillib
#f77  -o ../../../bin/atdep12_to_wqm57k_percent_of_CMAQ_scenario.exe main12_percent_of_existing_CMAQ.o getatdep12_percent_of_existing_CMAQ_scenario.o getcellarea.o $utillib

rm *.o
