#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o


$FC -fbounds-check -c quick_wdm_2_txt_hour_2_hour.f

$FC -o ../../../bin/quick_wdm_2_txt_hour_2_hour quick_wdm_2_txt_hour_2_hour.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
