#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c read_outfile.f

$FC -c main_read_ON_stor.f

$FC -o ../../../bin/read_dot_out_files.exe read_outfile.o main.o $usrlib

$FC -o ../../../bin/read_ON_stor.exe main_read_ON_stor.o $usrlib

rm *.o
