#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main_calib.f
$FC -fbounds-check -c main_scenario_from_csv.f

$FC -o ../../../bin/create_calib_ps_wdms.exe main_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3

$FC -o ../../../bin/create_scenario_ps_wdms_from_csv.exe main_scenario_from_csv.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
