#!/bin/csh

set usrdir = ../../../lib/
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c main.f
f77 -fbounds-check -c CalcBasinDFann.f
f77 -fbounds-check -c CalcBasinDFave.f
f77 -fbounds-check -c CalcBasinDFmon.f
f77 -fbounds-check -c CalcResDFann.f
f77 -fbounds-check -c CalcResDFave.f
f77 -fbounds-check -c CalcResDFmon.f
f77 -fbounds-check -c CalcSegDFann.f
f77 -fbounds-check -c CalcSegDFave.f
f77 -fbounds-check -c CalcSegDFmon.f
f77 -fbounds-check -c delinfo.f
f77 -fbounds-check -c downstream.f
f77 -fbounds-check -c findResBasin.f
f77 -fbounds-check -c findupstream.f
f77 -fbounds-check -c getloads.f
f77 -fbounds-check -c getRvars.f
f77 -fbounds-check -c multtfs.f
f77 -fbounds-check -c pourpoint.f
f77 -fbounds-check -c readtfinout.f
f77 -fbounds-check -c writedfs.f


f77 -o ../../../../bin/DFS.exe main.o CalcBasinDFann.o CalcBasinDFave.o CalcBasinDFmon.o CalcResDFann.o CalcResDFave.o CalcResDFmon.o CalcSegDFann.o CalcSegDFave.o CalcSegDFmon.o delinfo.o downstream.o findResBasin.o findupstream.o getloads.o getRvars.o multtfs.o pourpoint.o readtfinout.o writedfs.o $usrlib

rm *.o

