************************************************************************
** variables to work with HSPF modules                                **
************************************************************************
      integer nModMax           ! variables to get the modules
      parameter (nModMax = 12)      ! max modules
      character*6 modules(nModMax)         ! modules in use
      integer nmod

