#!/bin/csh

## set usrdir = ../../../lib
## set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c findcolumn.f
f77 -c allcolumns.f
f77 -c ioparvar.f
f77 -c getall.f
f77 -c getrivfacs.f
f77 -c zipall.f

ar rv caltemp.a findcolumn.o allcolumns.o ioparvar.o getall.o getrivfacs.o zipall.o 
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

f77 -c main.f

### this compile script only forms the objects.  The final linkage
###  is done in the run script that starts the whole iteration process
###  The objects in this directory are linked with function objects in
###  ./run/control/calib/$calscen/$calscen_sensitivities.o
