#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c getall.f
f77 -c process.f

f77 -o ../../../bin/make_calib_site_list.exe main.o getall.o process.o $usrlib

rm *.o
