#!/bin/csh
set FC = $argv[1]
$FC -fbounds-check -c chars.f
$FC -fbounds-check -c columnorder.f
$FC -fbounds-check -c comment.f
$FC -fbounds-check -c csv.f
$FC -fbounds-check -c dates.f
$FC -fbounds-check -c stopreport.f
$FC -fbounds-check -c wdm.f
$FC -fbounds-check -c writeline.f
$FC -fbounds-check -c fchar.f
$FC -fbounds-check -c findopen.f
$FC -fbounds-check -c correl.f
$FC -fbounds-check -c interpolate.f
$FC -fbounds-check -c readcontrol.f
$FC -fbounds-check -c sort.f
$FC -fbounds-check -c fipstate.f
$FC -fbounds-check -c addvector.f

ar rv ../util_lib.a chars.o columnorder.o comment.o csv.o dates.o findopen.o stopreport.o wdm.o writeline.o fchar.o correl.o interpolate.o readcontrol.o sort.o fipstate.o addvector.o

rm *.o
