#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

# $FC -c main.f
# $FC -c main_end_in_wateryear.f
# $FC -c main_end_in_wateryear_dry_dep_by_CMAQ_cell.f
# $FC -c main_wateryear_year_scenario.f
# $FC -c main_wateryear_year_scenario_with_factor.f
# $FC -c main_wateryear_cmaq_scenario.f
# $FC -c main_grimm03_CMAQ_ORG_PO4.f
# $FC -c main_grimm07_CMAQ36_ORG_PO4.f
# $FC -c main_g07_C36_O_P_year_scenario.f
# $FC -c main_g07_C36_O_P_CMAQ_scenario.f
$FC -fbounds-check -c main_grimm07_CMAQ12_ORG_PO4.f
$FC -fbounds-check -c main_g07_C12_O_P_year_scenario.f
$FC -fbounds-check -c main_g07_C12_O_P_CMAQ_scenario.f
$FC -fbounds-check -c main_pristine.f
$FC -fbounds-check -c main_percent_of_existing.f
$FC -fbounds-check -c main_percent_by_lseg.f
$FC -fbounds-check -c main_interpolate_2_existing.f

# $FC -o ../../../bin/add_atdep main.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_end_in_wateryear main_end_in_wateryear.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_end_in_wateryear_dry_dep_by_CMAQ_cell main_end_in_wateryear_dry_dep_by_CMAQ_cell.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_year_scenario main_wateryear_year_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_year_scenario_with_factor main_wateryear_year_scenario_with_factor.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_cmaq_scenario main_wateryear_cmaq_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_grimm03_CMAQ_ORG_PO4 main_grimm03_CMAQ_ORG_PO4.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_grimm07_CMAQ36_ORG_PO4 main_grimm07_CMAQ36_ORG_PO4.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_grimm07_CMAQ36_ORG_PO4_year_scenario main_g07_C36_O_P_year_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
# $FC -o ../../../bin/add_atdep_grimm07_CMAQ36_ORG_PO4_CMAQ_scenario main_g07_C36_O_P_CMAQ_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_grimm07_CMAQ12_ORG_PO4 main_grimm07_CMAQ12_ORG_PO4.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_grimm07_CMAQ12_ORG_PO4_year_scenario main_g07_C12_O_P_year_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_grimm07_CMAQ12_ORG_PO4_CMAQ_scenario main_g07_C12_O_P_CMAQ_scenario.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_pristine main_pristine.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_percent_of_existing main_percent_of_existing.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/add_atdep_interpolate_2_existing main_interpolate_2_existing.o $usrlib $dsnlib $lib1 $lib2 $lib3
$FC -o ../../../bin/reduce_atdep_percent_by_lseg main_percent_by_lseg.o $usrlib $dsnlib $lib1 $lib2 $lib3
rm *.o
