#!/bin/csh

source ../../set_wdmlibdir
set wdmlibdir = ../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set dsnlib = ../lib/dsn/dsn_utils.o

set usrdir = ../lib
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c main.f
f77 -fbounds-check -c readloads.f
f77 -fbounds-check -c readcontrolkey.f
f77 -fbounds-check -c readspeclu.f
f77 -fbounds-check -c rmMissingloads.f

f77 -o ../../bin/create_land_wdm_from_loads.exe main.o readloads.o readcontrolkey.o readspeclu.o rmMissingloads.o $usrlib $dsnlib $lib1 $lib2 $lib3 
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
