#!/bin/csh

set usrdir = ../../../lib
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c anntf.f
f77 -fbounds-check -c avetf.f
f77 -fbounds-check -c datann.f
f77 -fbounds-check -c datave.f
f77 -fbounds-check -c datmon.f
f77 -fbounds-check -c delinfo.f
f77 -fbounds-check -c getloads.f
f77 -fbounds-check -c getRvars.f
f77 -fbounds-check -c getsegload.f
f77 -fbounds-check -c getupstreamload.f
f77 -fbounds-check -c lsegann.f
f77 -fbounds-check -c lsegave.f
f77 -fbounds-check -c lsegmon.f
f77 -fbounds-check -c main.f
f77 -fbounds-check -c montf.f
f77 -fbounds-check -c readcontrol_dat.f
f77 -fbounds-check -c writetfs.f

f77 -o ../../../../bin/TFS_P6.exe main.o anntf.o avetf.o datann.o datave.o datmon.o delinfo.o getloads.o getRvars.o getsegload.o getupstreamload.o lsegann.o lsegave.o lsegmon.o montf.o readcontrol_dat.o writetfs.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

