#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c ioparvar.f
f77 -c getall.f
f77 -c minmax.f
f77 -c change_params.f

#f77 -o ../../../../../bin/calib_nitr_crop.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o minmax.o change_params.o read_storage.o change_wiltp.o getuptk.o change_lorgn.o change_rorgn.o read_rorgn.o $usrlib

f77 -o AssembleTargets.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o minmax.o change_params.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o



