#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c getall.f
f77 -c process.f

f77 -o ../../../bin/make_incremental_calib_list.exe main.o getall.o process.o $usrlib

rm *.o
