#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a

$FC -fbounds-check -c main.f
$FC -fbounds-check -c Rmasslink.f
$FC -fbounds-check -c checkflow.f
$FC -fbounds-check -c checktime.f
$FC -fbounds-check -c addRwdm.f
$FC -fbounds-check -c Rmasslink_confluence.f
$FC -fbounds-check -c confluence.f

$FC -o ../../../bin/stream_wdm.exe main.o Rmasslink.o checkflow.o checktime.o addRwdm.o ../../lib/dsn/dsn_utils.o $lib1 $lib2 $lib3 ../../lib/get_lib.a ../../lib/util_lib.a
$FC -o ../../../bin/confluence.exe confluence.o Rmasslink_confluence.o checktime.o checkflow.o addRwdm.o ../../lib/dsn/dsn_utils.o $lib1 $lib2 $lib3 ../../lib/get_lib.a ../../lib/util_lib.a

rm *.o

