#!/bin/csh
set FC = $argv[1]
set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c findcolumn.f
$FC -c getcolumns.f
$FC -c ioparvar.f
$FC -c getall.f
$FC -c minmax.f
$FC -c change_params.f
$FC -c read_storage.f
$FC -c change_lorgn.f
$FC -c change_rorgn.f
$FC -c read_rorgn.f

$FC -o ../../../../../bin/calib_nitr_alf.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o minmax.o change_params.o read_storage.o change_lorgn.o change_rorgn.o read_rorgn.o $usrlib


rm *.o



