#!/bin/bash
# note: using double brackets in bash, tip from SUGGESTIONS
#       section in https://stackoverflow.com/questions/18568706/check-number-of-arguments-passed-to-a-bash-script
if [[ $# -lt 3 ]]; then
  >&2 echo "Usage: get_config scenario type(river/land/script) varname"
  >&2 echo "Ex: get_config vadeq_2021 river IOVARS"
fi
scenario=$1
module=$2
varname=$3
conf_type="block"
if [[ "$module" == "script" ]]; then
  conf_type="line"
fi
if [[ "$module" == "met" ]]; then
  conf_type="line"
fi
if [[ "$conf_type" == "line" ]]; then
  . cbp_scenario_vars_bash ${scenario} ${varname} ${module}
else
  open_tag=$varname
  close_tag="END $open_tag"
  config_file="$CBP_ROOT/config/control/$module/${scenario}.con"
  >&2 echo "Searching for $open_tag $close_tag in $config_file"
  awk 'flag{
          if (/'"${close_tag}"'/)
             {printf "%s", buf; flag=0; buf=""}
          else
              buf = buf $0 ORS
       }
       /'"${open_tag}"'/ {flag=1}' $config_file | grep -v "*/*/*"
fi
