#!/bin/bash

hspf_config=`find_config hspf.config`
if [ "$hspf_config" = "" ]; then
  hspf_config="/etc/hspf.config"
fi

if [ "$HSPF_CONFIG_DEBUG" = "1" ]; then
  echo "Loading $hspf_config" 1>&2
fi
source $hspf_config

