#!/bin/bash
scenario=$1
segment=$2

#echo "job_name=`cbp mm_job_name $scenario $segment`"
if [ "$segment" = "" ]; then
  job_name=$1
else
  job_name=`cbp mm_job_name $scenario $segment`
fi
#echo "djid=$(squeue --noheader --format %i --name $job_name)"
djid=$(squeue --noheader --format %i --name $job_name)
echo $djid
