#!/bin/csh

source ../../../../set_wdmlibdir
set wdmlibdir = ../../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main.f
f77 -fbounds-check -c monthly.f
f77 -fbounds-check -c loadinfo.f

f77 -o ../../../../bin/Rallmonth.exe monthly.o loadinfo.o main.o $dsnlib $lib1 $lib2 $lib3 ../postriverlib.a $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

