#!/bin/csh

set usrdir = ../../../src/lib

set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c getconcname.f

f77 -o ../../../bin/split_single_seg_WQ_data.exe main.o getconcname.o $usrlib 

rm *.o
