#!/bin/csh

  set usrdir = ../../../../lib
  set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

  f77 -c main.f
  f77 -c readcontrol_vartypes.f

  f77 -o ../../../../../bin/pltgen_annave_summary.exe main.o readcontrol_vartypes.o $usrlib
  set failed = $status; if( $failed == 1 ) exit 1

  rm *.o

