#!/bin/csh

  set usrdir = ../../../lib
  set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

  f77 -fbounds-check -c main.f
  f77 -fbounds-check -c readcontrol_vartypes.f
  f77 -fbounds-check -c main_no_control.f

  f77 -o ../../../../bin/pltgen2cal.exe main.o readcontrol_vartypes.o $usrlib
  f77 -o ../../../../bin/pltgen2cal_no_control.exe main_no_control.o $usrlib

  rm *.o

