#!/bin/csh
set FC = $argv[1]
  set usrdir = ../../../lib
  set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

  $FC -fbounds-check -c main.f
  $FC -fbounds-check -c readcontrol_vartypes.f
  $FC -fbounds-check -c main_no_control.f

  $FC -o ../../../../bin/pltgen2cal.exe main.o readcontrol_vartypes.o $usrlib
  $FC -o ../../../../bin/pltgen2cal_no_control.exe main_no_control.o $usrlib

  rm *.o

