#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c getall.f
f77 -c process.f

f77 -o ../../../bin/riverinfo.exe main.o getall.o process.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -c stand_alone_get_all_rseg_lseg_percents.f
f77 -o ../../../bin/stand_alone_get_all_rseg_lseg_percents.exe stand_alone_get_all_rseg_lseg_percents.o getall.o process.o $usrlib

f77 -c stand_alone_get_downstream_foreach_rseg_lseg.f
f77 -o ../../../bin/stand_alone_get_downstream_foreach_rseg_lseg.exe stand_alone_get_downstream_foreach_rseg_lseg.o getall.o process.o $usrlib

f77 -c stand_alone_get_upstream.f
f77 -o ../../../bin/stand_alone_get_upstream.exe stand_alone_get_upstream.o getall.o process.o $usrlib

rm *.o
