#!/bin/csh

set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c proc.f
f77 -c findcolumn.f
f77 -c readcontrol_tree2paramscen.f
f77 -c doaction.f
f77 -c getthislutype.f

f77 -o ../../../bin/get1parameter.exe main.o proc.o findcolumn.o readcontrol_tree2paramscen.o doaction.o getthislutype.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
