#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c ioparvar.f
f77 -c getall.f
f77 -c minmax.f
f77 -c change_storage.f
f77 -c change_params.f
f77 -c read_storage.f

f77 -o ../../../../../bin/calib_nitr_noncrop.exe main.o findcolumn.o getcolumns.o getall.o ioparvar.o minmax.o change_storage.o change_params.o read_storage.o $usrlib

rm *.o



