#!/bin/csh
set FC = $argv[1]
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c main.f
$FC -c getall.f
$FC -c process.f

$FC -o ../../../bin/make_WQ_incremental_calib_list.exe main.o getall.o process.o $usrlib

rm *.o
