#!/bin/csh

set usrdir = ../../../src/lib

set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c getrsegs.f
f77 -c getconcname.f

f77 -o ../../../bin/split_WQ_data.exe main.o getrsegs.o getconcname.o $usrlib 

rm *.o
