#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set usrdir    = ../../lib/

set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrlib = ( $usrdir/get_lib.a $usrdir/util_lib.a )
set dsnlib = $usrdir/dsn/dsn_utils.o


f77 -fbounds-check -c main_detrend.f
f77 -o ../../../bin/Atdep_detrend.exe main_detrend.o $dsnlib $usrlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
