#!/bin/csh
### this compile script only forms the objects.  The final linkage
###  is done in the run script that starts the whole iteration process
###  The objects in this directory are linked with function objects in
###  ./run/control/calib/IQUAL/$calscen/$calscen_sensitivities.o

f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c getsimEOF.f
f77 -c gettarget.f
f77 -c ioparvar.f

ar rv calib_iter_IQUAL.a findcolumn.o getcolumns.o getsimEOF.o gettarget.o ioparvar.o 

rm *.o

f77 -c main.f
f77 -c main_assign_initial_params.f
f77 -c main_check_calib.f

