#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main_calib.f
f77 -fbounds-check -c readstdin.f
f77 -fbounds-check -c main_year_scenario_from_calib.f
f77 -fbounds-check -c main_add_2001-2003_diversions_to_calib.f
f77 -fbounds-check -c extract_diversions.f

f77 -o ../../../bin/quickcreate1wdm_convert_mgd_to_cfs main_calib.o readstdin.o $usrlib $dsnlib $lib1 $lib2 $lib3
f77 -o ../../../bin/create_year_scenario_diversions_from_calib main_year_scenario_from_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3
f77 -o ../../../bin/add_2001-2003_diversions_to_calib main_add_2001-2003_diversions_to_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3

f77 -o ../../../bin/extract_diversions.exe extract_diversions.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

# BHATT
f77 -fbounds-check -c extract_diversionsY1Y2.f
f77 -o ../../../bin/extract_diversionsY1Y2.exe extract_diversionsY1Y2.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -fbounds-check -c extract_diversionsY1asY2.f
f77 -o ../../../bin/extract_diversionsY1asY2.exe extract_diversionsY1asY2.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -fbounds-check -c copy_diversion_Y1asY2.f
f77 -o ../../../bin/copy_diversion_Y1asY2.exe copy_diversion_Y1asY2.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
