#!/bin/csh

 set usrdir = ../../../../lib
 set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set FC = $argv[1]
$FC -c findcolumn.f
$FC -c allcolumns.f
$FC -c ioparvar.f
$FC -c minmax.f
$FC -c getall.f
$FC -c getlufacs.f
$FC -c zipall.f
$FC -c printall.f

ar rv caltemp.a findcolumn.o allcolumns.o ioparvar.o minmax.o getall.o getlufacs.o zipall.o printall.o $usrlib

rm *.o

$FC -c main.f

### this compile script only forms the objects.  The final linkage
###  is done in the run script that starts the whole iteration process
###  The objects in this directory are linked with function objects in
###  ./run/control/calib/$calscen/$calscen_sensitivities.o
