#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

$FC -fbounds-check -c main.f
$FC -fbounds-check -c loadinfo.f
$FC -fbounds-check -c masslink.f
$FC -fbounds-check -c readcontrol_tmsce.f
$FC -fbounds-check -c writeEOannual.f
$FC -fbounds-check -c writeEOaveann.f
$FC -fbounds-check -c writeEOdaily.f
$FC -fbounds-check -c writeEOmonthly.f
$FC -fbounds-check -c readcontrol_load.f
$FC -fbounds-check -c getafoload.f

$FC -o ../../../bin/etm_and_postproc.exe main.o loadinfo.o masslink.o readcontrol_tmsce.o writeEOannual.o writeEOaveann.o writeEOdaily.o writeEOmonthly.o readcontrol_load.o getafoload.o $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o

