#!/bin/csh

set usrdir = ../../../src/lib

set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a $usrdir/ttyux.o)

f77 -c main.f
f77 -c getrsegs.f

f77 -o add_NO23_to_NO3X.exe main.o getrsegs.o $usrlib 

rm *.o
