#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

f77 -fbounds-check -c main_calib.f
f77 -fbounds-check -c main_scenario_from_csv.f

f77 -fbounds-check -c getSPARROWfacCOMID.f
f77 -fbounds-check -c main_calib_withSPARROW.f

f77 -fbounds-check -c getCSOPassThru.f
f77 -fbounds-check -c main_scenario_withSPARROW.f

f77 -o ../../../bin/create_calib_ps_wdms.exe main_calib.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../bin/create_scenario_ps_wdms_from_csv.exe main_scenario_from_csv.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../bin/create_calib_ps_wdms_withSPARROW.exe main_calib_withSPARROW.o getSPARROWfacCOMID.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../bin/create_scenario_ps_wdms_withSPARROW.exe main_scenario_withSPARROW.o getSPARROWfacCOMID.o getCSOPassThru.o $usrlib $dsnlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
