#!/bin/csh

  if (${#argv} != 1) then
    echo ' '
    echo 'usage:  compile calib_scenario '
    echo ' '
    exit
  endif

set calscen = $argv[1]
set usrdir = ../../../../../../code/src/lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c adddoubles.f
f77 -c concinfo.f
f77 -c findupstream.f
f77 -c getarea.f
f77 -c main.f
f77 -c weightfunction.f


f77 -o ../../../../../../code/bin/make_WQ_weights_${calscen}.exe adddoubles.o concinfo.o findupstream.o getarea.o main.o weightfunction.o $usrlib

rm *.o

