#!/bin/csh
set FC = $argv[1]
  set usrdir = ../../../lib
  set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

  $FC -fbounds-check -c main.f
  $FC -fbounds-check -c readcontrol_vartypes.f
  $FC -fbounds-check -c plt2cal.f

  $FC -o ../../../../bin/pltgen.exe main.o readcontrol_vartypes.o plt2cal.o $usrlib

  rm *.o

