#!/bin/csh

 set usrdir = ../../../../lib
 set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c changeriver.f
f77 -c concinfo.f
f77 -c getall.f
f77 -c param_list.f
f77 -c storegetnpnv.f
f77 -c updateparams.f
f77 -c initializeparams.f

f77 -c main_write_start_matrix.f
f77 -o ../../../../../bin/write_WQ_start_matrix.exe main_write_start_matrix.o concinfo.o getall.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -c main_update_river_sens_param_file.f
f77 -o ../../../../../bin/update_river_sens_param_file.exe main_update_river_sens_param_file.o getall.o param_list.o changeriver.o storegetnpnv.o updateparams.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -c main_write_river_sens_matrix.f
f77 -o ../../../../../bin/write_river_sens_matrix.exe main_write_river_sens_matrix.o concinfo.o getall.o storegetnpnv.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -c main_read_river_sens_matrix.f
f77 -o ../../../../../bin/read_river_sens_matrix.exe main_read_river_sens_matrix.o concinfo.o getall.o param_list.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

f77 -c main_initiate_river_sens_params.f
f77 -o ../../../../../bin/initialize_river_sens_param_files.exe main_initiate_river_sens_params.o concinfo.o changeriver.o initializeparams.o getall.o param_list.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

