#!/bin/csh
set FC = $argv[1]
 set usrdir = ../../../../lib
 set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

$FC -c changeriver.f
$FC -c concinfo.f
$FC -c getall.f
$FC -c param_list.f
$FC -c storegetnpnv.f
$FC -c updateparams.f
$FC -c initializeparams.f

$FC -c main_write_start_matrix.f
$FC -o ../../../../../bin/write_WQ_start_matrix.exe main_write_start_matrix.o concinfo.o getall.o $usrlib

$FC -c main_update_river_sens_param_file.f
$FC -o ../../../../../bin/update_river_sens_param_file.exe main_update_river_sens_param_file.o getall.o param_list.o changeriver.o storegetnpnv.o updateparams.o $usrlib

$FC -c main_write_river_sens_matrix.f
$FC -o ../../../../../bin/write_river_sens_matrix.exe main_write_river_sens_matrix.o concinfo.o getall.o storegetnpnv.o $usrlib

$FC -c main_read_river_sens_matrix.f
$FC -o ../../../../../bin/read_river_sens_matrix.exe main_read_river_sens_matrix.o concinfo.o getall.o param_list.o $usrlib

$FC -c main_initiate_river_sens_params.f
$FC -o ../../../../../bin/initialize_river_sens_param_files.exe main_initiate_river_sens_params.o concinfo.o changeriver.o initializeparams.o getall.o param_list.o $usrlib

rm *.o

