#!/bin/csh

set usrdir = ../../../lib
set usrlib = ($usrdir/ttyux.o $usrdir/get_lib.a $usrdir/util_lib.a)

f77 -fbounds-check -c main.f
f77 -fbounds-check -c delatdepann.f
f77 -fbounds-check -c delatdepave.f
f77 -fbounds-check -c delatdepmon.f
f77 -fbounds-check -c deldatann.f
f77 -fbounds-check -c deldatave.f
f77 -fbounds-check -c deldatmon.f
f77 -fbounds-check -c delinfo.f
f77 -fbounds-check -c dellsegann.f
f77 -fbounds-check -c dellsegave.f
f77 -fbounds-check -c dellsegmon.f
f77 -fbounds-check -c getdfs.f
f77 -fbounds-check -c getloads.f
f77 -fbounds-check -c getRvars.f
f77 -fbounds-check -c readcontrol_dat.f

f77 -o ../../../../bin/DEL_P6.exe main.o delatdepann.o delatdepave.o delatdepmon.o deldatann.o deldatave.o deldatmon.o delinfo.o dellsegann.o dellsegave.o dellsegmon.o getdfs.o getloads.o getRvars.o readcontrol_dat.o $usrlib
set failed = $status; if( $failed == 1 ) exit 1

rm *.o

