#!/bin/csh
set FC = $argv[1]
source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o
set wqmlib = ../wqmlib/wqmlib.a

$FC -c main_nps_and_ps_together.f

$FC  -o ../../../bin/TMDL_daily_loads.exe main_nps_and_ps_together.o $wqmlib $usrlib $dsnlib $lib1 $lib2 $lib3

rm *.o
