#!/bin/csh

set usrdir = ../../../../lib
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)

f77 -c main.f
f77 -c findcolumn.f
f77 -c getcolumns.f
f77 -c getkserfac.f
f77 -c gettargets.f
f77 -c ioparvar.f
f77 -c getparmrules.f

f77 -o ../../../../../bin/calib_SEDMNT_1lu_wFourParameters.exe main.o findcolumn.o getcolumns.o getkserfac.o gettargets.o ioparvar.o getparmrules.o $usrlib

rm *.o



