#!/bin/csh

source ../../../set_wdmlibdir
set wdmlibdir = ../../$wdmlibdir
set lib1 = $wdmlibdir/wdmlib.a
set lib2 = $wdmlibdir/adwdmlib.a
set lib3 = $wdmlibdir/utillib.a
set usrdir = ../../lib/
set usrlib = ($usrdir/get_lib.a $usrdir/util_lib.a)
set dsnlib = ../../lib/dsn/dsn_utils.o

 f77 -fbounds-check -c main_create_precip_wdms.f
 f77 -fbounds-check -c change_precip_for_Nov1985_storm.f

f77 -o ../../../bin/create_precip_wdms main_create_precip_wdms.o $dsnlib $usrlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

f77 -o ../../../bin/change_precip_for_Nov1985_storm change_precip_for_Nov1985_storm.o $dsnlib $usrlib $lib1 $lib2 $lib3
set failed = $status; if( $failed == 1 ) exit 1

rm *.o
