#!/bin/csh

 f77 -fbounds-check -c main.f
 f77 -fbounds-check -c avesums.f

 f77 -o ../../../../../bin/sumsumstats.exe main.o avesums.o ../../../../lib/util_lib.a
 set failed = $status; if( $failed == 1 ) exit 1

 rm *.o

